name: Release

on:
  - workflow_dispatch

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@wlocalhost'
          always-auth: true

      - name: Setup Git
        run: |
          git config user.name "GitHub Bot"
          git config user.email "support@wlocalhost.org"
          git branch -a

      - name: Install deps
        run: |
          npm ci

      - name: Prerelease
        if: github.ref_name == 'beta'
        shell: bash
        run: |
          npm whoami
          npx nx run-many --all --base=beta --baseBranch=beta --exclude=bootstrap-email-builder --target=version --releaseAs=prerelease --preid=beta --trackDeps --push --skipCommit
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release
        if: github.ref_name == 'main'
        shell: bash
        run: |
          npm whoami
          npx nx run-many --all --base=main --exclude=bootstrap-email-builder --target=version --trackDeps --push --skipCommit
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
